version: "3.7"
services:

    local-php:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: local-php
        image: php-image:v1
        volumes:
            - /var/www:/var/www/html
        network_mode: "bridge"
        ports:
            - "9000"


    local-memcached:
        build:
            context: ./memcached
            dockerfile: Dockerfile
        depends_on: 
            - local-php
        container_name: local-memcached
        image: memcached-image:v1
        network_mode: "service:local-php"


    local-redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        depends_on: 
            - local-php
        container_name: local-redis
        image: redis-image:v1
        network_mode: "service:local-php"
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/etc/redis/redis.conf:ro
        command: [ "redis-server", "/etc/redis/redis.conf" ]
        

    local-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:
            - local-php
        container_name: local-nginx
        image: nginx-image:v1
        links: 
            - local-php:php
        volumes:
            - /var/www:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        network_mode: "bridge"
        ports:
            - "80:80"


    local-mysql:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: local-mysql
        image: mysql-image:v1
        volumes:
            - ./mysql/data:/var/lib/mysql
        network_mode: "bridge"
        ports:
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
