version: "3.7"
services:

    local-javaweb:
        build:
            context: ./javaweb
            dockerfile: Dockerfile
        container_name: local-javaweb
        image: javaweb-image:v1
        network_mode: "bridge"
        ports:
            - "8080:8080"


    local-memcached:
        build:
            context: ./memcached
            dockerfile: Dockerfile
        container_name: local-memcached
        image: memcached-image:v1
        network_mode: "bridge"
        ports:
            - "11211:11211"


    local-redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        container_name: local-redis
        image: redis-image:v1
        network_mode: "bridge"
        ports:
            - "6379:6379"
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/etc/redis/redis.conf:ro
        command: [ "redis-server", "/etc/redis/redis.conf" ]
        

    local-mysql:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: local-mysql
        image: mysql-image:v1
        volumes:
            - ./mysql/data:/var/lib/mysql
        network_mode: "bridge"
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
